<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-android</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
		<ApplicationId>com.CompanyName.AvaloniaKit</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.3</ApplicationDisplayVersion>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
	</PropertyGroup>

	<ItemGroup>
		<AndroidResource Include="Icon.png">
			<Link>Resources\drawable\Icon.png</Link>
		</AndroidResource>
	</ItemGroup>

	<ItemGroup>
		<!-- Android 平台专用包 -->
		<PackageReference Include="Avalonia.Android" />
		<PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
		<!-- 显式引用以对齐 core-ktx 与 core 版本（避免 D8 重复类） -->
		<PackageReference Include="Xamarin.AndroidX.Core.Core.Ktx" />
		<PackageReference Include="SkiaSharp" />
		<PackageReference Include="SkiaSharp.NativeAssets.Android" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AvaloniaKit\AvaloniaKit.csproj" />
	</ItemGroup>
</Project>
