<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="Irihi.Ursa" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\UserControls\Discover\Games\GameBoxesUserControl.axaml.cs">
      <DependentUpon>GameBoxesUserControl.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\UserControls\Discover\Games\TetrisUserControl.axaml.cs">
      <DependentUpon>TetrisUserControl.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
